"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TCRequest(google.protobuf.message.Message):
    """/ Message sent by the REST frontend and by the controller.  It contains all the parameters of the
    / request.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_VIDEO_FIELD_NUMBER: builtins.int
    OUTPUT_VIDEO_FIELD_NUMBER: builtins.int
    BITRATE_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    input_video: builtins.str
    """/ The name of the input video."""
    output_video: builtins.str
    """/ The name of the output video."""
    bitrate: builtins.int
    """/ The desired birate in bit per second."""
    speed: builtins.str
    """/ How fast/slow should the enconding process be."""
    def __init__(
        self,
        *,
        input_video: builtins.str = ...,
        output_video: builtins.str = ...,
        bitrate: builtins.int = ...,
        speed: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bitrate", b"bitrate", "input_video", b"input_video", "output_video", b"output_video", "speed", b"speed"]) -> None: ...

global___TCRequest = TCRequest

@typing_extensions.final
class TCRequestReply(google.protobuf.message.Message):
    """/ Response for the submit_request method (sent from the controller to the REST API)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """/ True means no error, false means error."""
    error_message: builtins.str
    """/ If success is false, this field contains the error message."""
    request_id: builtins.str
    """/ The UUID for this request."""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
        request_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_message", b"error_message", "request_id", b"request_id", "success", b"success"]) -> None: ...

global___TCRequestReply = TCRequestReply

@typing_extensions.final
class RequestID(google.protobuf.message.Message):
    """/ Message sent by the REST frontend.  It contains only the request ID"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: builtins.int
    request_id: builtins.str
    def __init__(
        self,
        *,
        request_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["request_id", b"request_id"]) -> None: ...

global___RequestID = RequestID

@typing_extensions.final
class RequestIDList(google.protobuf.message.Message):
    """/ Response for the get_requests method (sent from the controller to the REST API)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_IDS_FIELD_NUMBER: builtins.int
    @property
    def request_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """/ The list of the request IDs."""
    def __init__(
        self,
        *,
        request_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["request_ids", b"request_ids"]) -> None: ...

global___RequestIDList = RequestIDList

@typing_extensions.final
class TCRequestStatus(google.protobuf.message.Message):
    """/ Response for the get_request_status method (sent from the controller to the REST API)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RequestStatusEnum:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RequestStatusEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TCRequestStatus._RequestStatusEnum.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INVALID: TCRequestStatus._RequestStatusEnum.ValueType  # 0
        """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
        WAITING: TCRequestStatus._RequestStatusEnum.ValueType  # 1
        """/ The request is waiting for a worker to proceess it."""
        STARTED: TCRequestStatus._RequestStatusEnum.ValueType  # 3
        """/ A worker has started transcoding the video."""
        COMPLETED: TCRequestStatus._RequestStatusEnum.ValueType  # 4
        """/ The worker has successfully uploaded the ouput file."""
        ERROR: TCRequestStatus._RequestStatusEnum.ValueType  # 5
        """/ There was an error when processing the request."""
        NOT_FOUND: TCRequestStatus._RequestStatusEnum.ValueType  # 6
        """/ The requested ID given by the user is unknonw."""

    class RequestStatusEnum(_RequestStatusEnum, metaclass=_RequestStatusEnumEnumTypeWrapper): ...
    INVALID: TCRequestStatus.RequestStatusEnum.ValueType  # 0
    """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
    WAITING: TCRequestStatus.RequestStatusEnum.ValueType  # 1
    """/ The request is waiting for a worker to proceess it."""
    STARTED: TCRequestStatus.RequestStatusEnum.ValueType  # 3
    """/ A worker has started transcoding the video."""
    COMPLETED: TCRequestStatus.RequestStatusEnum.ValueType  # 4
    """/ The worker has successfully uploaded the ouput file."""
    ERROR: TCRequestStatus.RequestStatusEnum.ValueType  # 5
    """/ There was an error when processing the request."""
    NOT_FOUND: TCRequestStatus.RequestStatusEnum.ValueType  # 6
    """/ The requested ID given by the user is unknonw."""

    REQUEST_STATUS_FIELD_NUMBER: builtins.int
    request_status: global___TCRequestStatus.RequestStatusEnum.ValueType
    """/ The type of the event"""
    def __init__(
        self,
        *,
        request_status: global___TCRequestStatus.RequestStatusEnum.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["request_status", b"request_status"]) -> None: ...

global___TCRequestStatus = TCRequestStatus

@typing_extensions.final
class WorkerID(google.protobuf.message.Message):
    """/ Message sent by the REST frontend.  It contains only the worker ID"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: builtins.int
    worker_id: builtins.str
    def __init__(
        self,
        *,
        worker_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker_id", b"worker_id"]) -> None: ...

global___WorkerID = WorkerID

@typing_extensions.final
class WorkerIDList(google.protobuf.message.Message):
    """/ Response for the get_workers method (sent from the controller to the REST API)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WORKER_IDS_FIELD_NUMBER: builtins.int
    @property
    def worker_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """/ The list of the worker IDs."""
    def __init__(
        self,
        *,
        worker_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker_ids", b"worker_ids"]) -> None: ...

global___WorkerIDList = WorkerIDList

@typing_extensions.final
class WorkerFullDesc(google.protobuf.message.Message):
    """/ Response for the get_worker method (sent from the controller to the REST API)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    CPUS_FIELD_NUMBER: builtins.int
    MEMORY_FIELD_NUMBER: builtins.int
    NODE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """/ The name of the worker."""
    id: builtins.str
    """/ The id of the worker."""
    cpus: builtins.str
    """/ The number of vcpus of the worker."""
    memory: builtins.str
    """/ The memory of the worker."""
    node: builtins.str
    """/ The node running the worker."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        id: builtins.str = ...,
        cpus: builtins.str = ...,
        memory: builtins.str = ...,
        node: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["cpus", b"cpus", "id", b"id", "memory", b"memory", "name", b"name", "node", b"node"]) -> None: ...

global___WorkerFullDesc = WorkerFullDesc

@typing_extensions.final
class WorkerGrpcState(google.protobuf.message.Message):
    """/ Response for the get_request_status method (sent from the controller to the REST API)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _WorkerStatusEnum:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _WorkerStatusEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[WorkerGrpcState._WorkerStatusEnum.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INVALID: WorkerGrpcState._WorkerStatusEnum.ValueType  # 0
        """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
        BOOTING: WorkerGrpcState._WorkerStatusEnum.ValueType  # 1
        """/ The worker is booting."""
        DOWNLOADING_FILE: WorkerGrpcState._WorkerStatusEnum.ValueType  # 2
        """/ The worker is downloading a file."""
        TRANSCODING: WorkerGrpcState._WorkerStatusEnum.ValueType  # 3
        """/ The worker is transcoding a video."""
        UPLOADING_FILE: WorkerGrpcState._WorkerStatusEnum.ValueType  # 4
        """/ The worker is uploading the ouput file."""
        IDLE: WorkerGrpcState._WorkerStatusEnum.ValueType  # 5
        """/ The worker is idle."""
        STOPPED: WorkerGrpcState._WorkerStatusEnum.ValueType  # 6
        """/ The worker has been deleted."""
        NOT_FOUND: WorkerGrpcState._WorkerStatusEnum.ValueType  # 7
        """/ The worker ID given by the user is unknonw."""

    class WorkerStatusEnum(_WorkerStatusEnum, metaclass=_WorkerStatusEnumEnumTypeWrapper): ...
    INVALID: WorkerGrpcState.WorkerStatusEnum.ValueType  # 0
    """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
    BOOTING: WorkerGrpcState.WorkerStatusEnum.ValueType  # 1
    """/ The worker is booting."""
    DOWNLOADING_FILE: WorkerGrpcState.WorkerStatusEnum.ValueType  # 2
    """/ The worker is downloading a file."""
    TRANSCODING: WorkerGrpcState.WorkerStatusEnum.ValueType  # 3
    """/ The worker is transcoding a video."""
    UPLOADING_FILE: WorkerGrpcState.WorkerStatusEnum.ValueType  # 4
    """/ The worker is uploading the ouput file."""
    IDLE: WorkerGrpcState.WorkerStatusEnum.ValueType  # 5
    """/ The worker is idle."""
    STOPPED: WorkerGrpcState.WorkerStatusEnum.ValueType  # 6
    """/ The worker has been deleted."""
    NOT_FOUND: WorkerGrpcState.WorkerStatusEnum.ValueType  # 7
    """/ The worker ID given by the user is unknonw."""

    WORKER_STATUS_FIELD_NUMBER: builtins.int
    worker_status: global___WorkerGrpcState.WorkerStatusEnum.ValueType
    """/ The type of the event"""
    def __init__(
        self,
        *,
        worker_status: global___WorkerGrpcState.WorkerStatusEnum.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["worker_status", b"worker_status"]) -> None: ...

global___WorkerGrpcState = WorkerGrpcState

@typing_extensions.final
class gRPCServiceReply(google.protobuf.message.Message):
    """/ Reply messsage from the server to the client and to the workers.  Indicates
    / whethere the request succeeded or not.  In case of failure, it contains an
    / error message.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """/ True means no error, false means error."""
    error_message: builtins.str
    """/ If success is false, this field contains the error message."""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_message", b"error_message", "success", b"success"]) -> None: ...

global___gRPCServiceReply = gRPCServiceReply

@typing_extensions.final
class WorkerDesc(google.protobuf.message.Message):
    """/ It uniquily identifies a transcoding worker.  Sent in calls from the workers
    / to the server so that the server can tell which worker is the sender of the
    / message.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    name: builtins.str
    """/ The name of the worker (it should be unique but it is not strictly needed)."""
    id: builtins.str
    """/ The UUID of the worker (MUST BE UNIQUE)"""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "name", b"name"]) -> None: ...

global___WorkerDesc = WorkerDesc

@typing_extensions.final
class TCTask(google.protobuf.message.Message):
    """/ Sent from the server to the workers.  It identifies a single transcoding
    / task.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INPUT_VIDEO_FIELD_NUMBER: builtins.int
    OUTPUT_VIDEO_FIELD_NUMBER: builtins.int
    BITRATE_FIELD_NUMBER: builtins.int
    SPEED_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    WORKER_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    input_video: builtins.str
    """/ The name of the input video."""
    output_video: builtins.str
    """/ The name of the output video."""
    bitrate: builtins.int
    """/ The desired bitrate."""
    speed: builtins.str
    """/ How fast the transcoding process should be."""
    request_id: builtins.str
    """/ The UUID of the request."""
    worker_id: builtins.str
    """/ The UUID of the worker to which this task has been assigned."""
    task_id: builtins.str
    """/ The unique identifier of this task."""
    def __init__(
        self,
        *,
        input_video: builtins.str = ...,
        output_video: builtins.str = ...,
        bitrate: builtins.int = ...,
        speed: builtins.str = ...,
        request_id: builtins.str = ...,
        worker_id: builtins.str = ...,
        task_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bitrate", b"bitrate", "input_video", b"input_video", "output_video", b"output_video", "request_id", b"request_id", "speed", b"speed", "task_id", b"task_id", "worker_id", b"worker_id"]) -> None: ...

global___TCTask = TCTask

@typing_extensions.final
class GrpcEvent(google.protobuf.message.Message):
    """/ Sent from a worker to the server.  It contains the worker and task id so that the 
    / server knows which worker and which task have generated this event
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _GrpcEventTypeEnum:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GrpcEventTypeEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GrpcEvent._GrpcEventTypeEnum.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INVALID: GrpcEvent._GrpcEventTypeEnum.ValueType  # 0
        """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
        FILE_DOWNLOADED: GrpcEvent._GrpcEventTypeEnum.ValueType  # 1
        """/ The worker has successfully dowloaded the input file."""
        TRANSCODING_COMPLETED: GrpcEvent._GrpcEventTypeEnum.ValueType  # 3
        """/ The worker has successfully transcoded the video."""
        FILE_UPLOADED: GrpcEvent._GrpcEventTypeEnum.ValueType  # 4
        """/ The worker has successfully uploaded the ouput file."""
        KEEPALIVE: GrpcEvent._GrpcEventTypeEnum.ValueType  # 5
        """/ The worker is still alive."""

    class GrpcEventTypeEnum(_GrpcEventTypeEnum, metaclass=_GrpcEventTypeEnumEnumTypeWrapper): ...
    INVALID: GrpcEvent.GrpcEventTypeEnum.ValueType  # 0
    """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
    FILE_DOWNLOADED: GrpcEvent.GrpcEventTypeEnum.ValueType  # 1
    """/ The worker has successfully dowloaded the input file."""
    TRANSCODING_COMPLETED: GrpcEvent.GrpcEventTypeEnum.ValueType  # 3
    """/ The worker has successfully transcoded the video."""
    FILE_UPLOADED: GrpcEvent.GrpcEventTypeEnum.ValueType  # 4
    """/ The worker has successfully uploaded the ouput file."""
    KEEPALIVE: GrpcEvent.GrpcEventTypeEnum.ValueType  # 5
    """/ The worker is still alive."""

    EVENT_TYPE_FIELD_NUMBER: builtins.int
    WORKER_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    event_type: global___GrpcEvent.GrpcEventTypeEnum.ValueType
    """/ The type of the event"""
    worker_id: builtins.str
    """/ The UUID of the worker."""
    task_id: builtins.str
    """/ The UUID of the task."""
    def __init__(
        self,
        *,
        event_type: global___GrpcEvent.GrpcEventTypeEnum.ValueType = ...,
        worker_id: builtins.str = ...,
        task_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["event_type", b"event_type", "task_id", b"task_id", "worker_id", b"worker_id"]) -> None: ...

global___GrpcEvent = GrpcEvent

@typing_extensions.final
class GrpcErrorEvent(google.protobuf.message.Message):
    """/ Sent from a worker to the server. It contains the worker and task id so that the 
    / server knows which worker and which task have generated this event
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _GrpcErrorType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GrpcErrorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GrpcErrorEvent._GrpcErrorType.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        INVALID: GrpcErrorEvent._GrpcErrorType.ValueType  # 0
        """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
        TRANSCODING_FAILED: GrpcErrorEvent._GrpcErrorType.ValueType  # 1
        """/ ffmpeg returned an error."""
        STORAGE_ERROR: GrpcErrorEvent._GrpcErrorType.ValueType  # 2
        """/ The storage system returned an error."""

    class GrpcErrorType(_GrpcErrorType, metaclass=_GrpcErrorTypeEnumTypeWrapper): ...
    INVALID: GrpcErrorEvent.GrpcErrorType.ValueType  # 0
    """/ O is the default value, this way we are sure that we are not going to send a message with the wrong type."""
    TRANSCODING_FAILED: GrpcErrorEvent.GrpcErrorType.ValueType  # 1
    """/ ffmpeg returned an error."""
    STORAGE_ERROR: GrpcErrorEvent.GrpcErrorType.ValueType  # 2
    """/ The storage system returned an error."""

    ERROR_TYPE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    WORKER_ID_FIELD_NUMBER: builtins.int
    TASK_ID_FIELD_NUMBER: builtins.int
    error_type: global___GrpcErrorEvent.GrpcErrorType.ValueType
    """The type of the error."""
    error_message: builtins.str
    """/ The error message."""
    worker_id: builtins.str
    """/ The UUID of the worker."""
    task_id: builtins.str
    """/ The UUID of the task."""
    def __init__(
        self,
        *,
        error_type: global___GrpcErrorEvent.GrpcErrorType.ValueType = ...,
        error_message: builtins.str = ...,
        worker_id: builtins.str = ...,
        task_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_message", b"error_message", "error_type", b"error_type", "task_id", b"task_id", "worker_id", b"worker_id"]) -> None: ...

global___GrpcErrorEvent = GrpcErrorEvent

@typing_extensions.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty
